#pragma once

#ifdef TUT2
	#include "tutorial2.h"
#elif TUT3
	#include "tutorial3.h"
#elif TUT4
	#include "tutorial4.h"
#elif TUT5
	#include "tutorial5.h"
#elif TUT6
	#include "tutorial6.h"
#elif TUT7
	#include "tutorial7.h"
#elif TUT8
	#include "tutorial8.h"
#elif TUT9
	#include "tutorial9.h"
#elif TUT10
	#include "tutorial10.h"
#elif TUT11
	#include "tutorial11.h"
#elif TUT12
	#include "tutorial12.h"
#elif TUT12t
	#include "tutorial12t.h"
#elif TUT13
	#include "tutorial13.h"
#elif TUT13t
	#include "tutorial13t.h"
#elif TUT14
	#include "tutorial14.h"
#elif TUT15
	#include "tutorial15.h"
#endif